name: build-on-pull-request
run-name: Build on Pull Request by ${{ github.actor }}
on:
  pull_request:
    branches:    
      - main

jobs:
  build-angular-app:
    - name: Set Env files
      working-directory: ./server
      run: node server.js
      env:
        DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
      uses: build-node.yml@main
      with:
        working-directory: ./angular-app
  build-code-ui:
    - name: Set Env files
      working-directory: ./server
      run: node server.js
      env:
        DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
      uses: build-node.yml@main
      with:
        working-directory: ./code-ui