name: build-on-pull-request
run-name: Build on Pull Request by ${{ github.actor }}
on:
  pull_request:
    branches:    
      - main

jobs:
  set-env-vars:
    name: generating env variable
    working-directory: ./server
    run: node server.js
    env:
      DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
  build-angular-app:
    uses: ./.github/workflows/build-node.yml
    with:
      working-directory: ./angular-app
  # build-code-ui:
  #   - name: run angular app
  #     working-directory: ./server
  #     run: node server.js
  #     env:
  #       DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
  #   - uses: ./.github/workflows/build-node.yml
  #     with:
  #       working-directory: ./code-ui