name: build-on-pull-request
run-name: Build on Pull Request by ${{ github.actor }}
on:
  pull_request:
    branches:    
      - main

jobs:
  build-angular-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: run angular app
        working-directory: ./server
        run: node server.js
        env:
          DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
      - uses: ./.github/workflows/build-node.yml
        with:
          working-directory: ./angular-app
  # build-code-ui:
  #   - name: run angular app
  #     working-directory: ./server
  #     run: node server.js
  #     env:
  #       DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
  #   - uses: ./.github/workflows/build-node.yml
  #     with:
  #       working-directory: ./code-ui