name: build-on-pull-request
run-name: Build on Pull Request by ${{ github.actor }}
on:
  pull_request:
    branches:    
      - main

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: seting cdk json in a variable
        working-directory: ./.cdk
      - name: Get version
        run: echo "version=$(cat cdk.json)" >> $GITHUB_OUTPUT
      - name: Test output
        env:
          DEV_ENV_VARS: ${{ steps.outputs.version.local.DomainName }}
        run: echo ${{ steps.outputs.version.local.DomainName }}
      - name: generating env variable
        working-directory: ./server
        run: node server.js

  build-angular-app:
    uses: ./.github/workflows/build-node.yml
    with:
      working-directory: ./angular-app
  # build-code-ui:
  #   - name: run angular app
  #     working-directory: ./server
  #     run: node server.js
  #     env:
  #       DEV_ENV_VARS: "${{ vars.DEV_ENV_VARS }}"
  #   - uses: ./.github/workflows/build-node.yml
  #     with:
  #       working-directory: ./code-ui