name: deploy-on-push
run-name: Deploy on Push by ${{ github.actor }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev-account:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: create env file
        env:
          DEV_DETAILS: "${{ secrets.DEV_ENV_VARS }}"
        run: |
          touch .env
          echo DEV_DETAILS=${{ secrets.DEV_ENV_VARS }} >> .env
      
      -name: print env var
        working-directory: ./server
        run: echo "The API key is:${{env.DEV_DETAILS}}" && echo "${{ secrets.DEV_ENV_VARS }}"

      - name: Set Env files
        working-directory: ./server
        run: node server.js

      # Build app
      - name: Build app
        working-directory: ./angular-app
        run: npm install && npm run build

      # Build UI
      # - name: Build ui
      #   working-directory: ./code-ui
      #   run: npm install && npm run build --configuration development
